#!/bin/sh

shellinaboxd --localhost-only --no-beep --css=shellinabox.css --disable-ssl --port=$1 --css=shellinabox.css --service "/:mrichar1:mrichar1:/:KRB5CCNAME=${KRB5CCNAME} SSH_AUTH_SOCK=${SSH_AUTH_SOCK} /usr/bin/ssh -o StrictHostKeyChecking=no $2"

